version: 2
jobs:
  build:
    working_directory: ~/megamillions-group
    docker:
    - image: circleci/python:3.6.1
      environment:
        PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python3 ./manage.py makemigrations
            python3 ./manage.py migrate
            python3 ./manage.py test
      - run:
          command: |
            . venv/bin/activate
            python3 ./manage.py test
      - run: mkdir test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
